# Run keycloak server
# docker compose --profile default up

# Export realm configuration
# docker compose --profile export-realm up

volumes:
  kc-db:

services:

  # keycloak pg db
  kc-db:
    image: "postgres:17-alpine"
    profiles:
      - export-realm
      - default
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_pw
      - POSTGRES_DB=keycloak
    volumes:
      - kc-db:/var/lib/postgresql/data

  # keycloak server
  keycloak:
    image: "quay.io/keycloak/keycloak:26.1.2"
    profiles:
      - default
    ports:
      - "8080:8080"
    environment:
      # db
      - KC_DB=postgres
      - KC_DB_URL_HOST=kc-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_pw

      # admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./realms:/opt/keycloak/data/import
    depends_on:
      - kc-db

  # Export keycloak realm to ./realms
  keycloak-export:
    image: "quay.io/keycloak/keycloak:26.1.2"
    profiles:
      - export-realm
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=kc-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_pw

    command: [ "export", "--realm", "test-realm" ,"--dir", "/var/export", "--verbose"]
    volumes:
      - ./realms:/var/export
    depends_on:
      - kc-db
