# Local dev configuration, suitable to migrate the local db in docker
flyway.user=kcsb
flyway.password=changeme
flyway.url=jdbc:postgresql://app-db:5432/kcsb
flyway.outOfOrder=true
flyway.locations=filesystem:/flyway/sql
flyway.connectRetries=60

# TODO: consider running flyway repair instead of turning this off?
flyway.validateOnMigrate=false
