api:
  insecure: true

entrypoints:
  web:
    address: :80

  websecure:
    address: :443

certificatesResolvers:
  ob-acme:
    acme:
      storage: acme.json
      caServer: http://ob:8200/v1/acme-pki/directory
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik/dynamic/

accessLog:
  format: json
  filePath: /var/log/traefik/access.json

tracing:
  serviceName: traefik
  sampleRate: 1.0
  otlp:
    grpc:
      insecure: true
      endpoint: "aspire:18889"
