api:
  insecure: true

entrypoints:
  web:
    address: :80

providers:
  file:
    directory: /etc/traefik/dynamic/

accessLog:
  format: json
  filePath: /var/log/traefik/access.json

tracing:
  serviceName: traefik
  sampleRate: 1.0
  otlp:
    grpc:
      insecure: true
      endpoint: "aspire:18889"
